// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ciqgxeycenyqmmmyodae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpcWd4ZXljZW55cW1tbXlvZGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjI1ODgsImV4cCI6MjA3MDIzODU4OH0.LoWXgFQHzDwB-08Ud06tDXHvbyznNU6TeqasfZqrfz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});